# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 843ddca257ab79ac4daf1a86e78e47909e9aa54545b12448bddcab51aaca6e1786cf3177711aa5526e168c05d333cf7753d5d276db761ca2aec2c9e6c67a866e

test:
  secret_key_base: 68c9cb1a6b07ec4ed8233365e24fc52491026a41e080c262c201fa3de28d89b720589e436886cdee73e749b371577e819e30014bb9b75475cf66a4c472739926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
